# Generated by Django 2.1.10 on 2019-08-21 15:04

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.utils.timezone
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('direccio', djrichtextfield.models.RichTextField()),
                ('poblacio', models.CharField(max_length=255)),
                ('cp', models.CharField(max_length=5)),
                ('telefon', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('web', models.URLField(blank=True)),
                ('localitzacio', django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(2.6875, 41.56), srid=4326)),
                ('descripcio', djrichtextfield.models.RichTextField(blank=True)),
                ('imatge', models.ImageField(blank=True, upload_to='imatgesCentre')),
            ],
            options={
                'verbose_name_plural': 'Empreses',
            },
        ),
        migrations.CreateModel(
            name='Notificacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registre', models.TextField(blank=True)),
                ('enviament', models.DateTimeField(blank=True, null=True)),
                ('confirmacio', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Notificacions',
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inici', models.DateTimeField(default=django.utils.timezone.now)),
                ('final', models.DateTimeField()),
                ('activa', models.BooleanField(default=True)),
                ('titol', models.CharField(max_length=255)),
                ('descripcio', djrichtextfield.models.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Ofertes',
            },
        ),
        migrations.CreateModel(
            name='Subscripcio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.FloatField(default=0.0, help_text='Si la distància és 0 no es tindrà en compte aquest paràmetre')),
                ('creat', models.DateTimeField(auto_now_add=True)),
                ('modificat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Subscripcions',
            },
        ),
        migrations.CreateModel(
            name='Titol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduat', models.BooleanField()),
                ('data', models.DateField(blank=True, help_text="Data de graduació de l'alumne", null=True)),
                ('descripcio', djrichtextfield.models.RichTextField(blank=True)),
            ],
        ),
    ]
