# Generated by Django 2.1.10 on 2019-08-21 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('borsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='titol',
            name='alumne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titols', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='titol',
            name='centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Centre'),
        ),
        migrations.AddField(
            model_name='titol',
            name='cicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Cicle'),
        ),
        migrations.AddField(
            model_name='subscripcio',
            name='alumne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscripcio',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Rebre les ofertes que estiguin en aquestes categories', to='core.Categoria'),
        ),
        migrations.AddField(
            model_name='subscripcio',
            name='centre_educatiu',
            field=models.ForeignKey(blank=True, help_text='Rebre les ofertes dirigides a aquest centre', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscripcions', to='core.Centre'),
        ),
        migrations.AddField(
            model_name='subscripcio',
            name='centre_treball',
            field=models.ForeignKey(blank=True, help_text="Rebre les ofertes d'aquesta empresa", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscipcions', to='borsApp.Empresa'),
        ),
        migrations.AddField(
            model_name='subscripcio',
            name='cicles',
            field=models.ManyToManyField(help_text='Rebre les ofertes relacionades amb aquests cicles', to='core.Cicle'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='cicles',
            field=models.ManyToManyField(to='core.Cicle'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oferta',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='borsApp.Empresa'),
        ),
        migrations.AddField(
            model_name='notificacio',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borsApp.Oferta'),
        ),
        migrations.AddField(
            model_name='notificacio',
            name='usuari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresa',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='empreses_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresa',
            name='adscripcio',
            field=models.ManyToManyField(blank=True, help_text="Centres educatius als que està adscrita l'empresa. ", related_name='empreses', to='core.Centre'),
        ),
        migrations.AlterUniqueTogether(
            name='notificacio',
            unique_together={('oferta', 'usuari')},
        ),
    ]
