# Generated by Django 2.2.4 on 2019-09-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_centre_codi'),
        ('borsApp', '0002_auto_20190821_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='categories',
            field=models.ManyToManyField(blank=True, to='core.Categoria'),
        ),
    ]
