# Generated by Django 2.1.10 on 2019-08-21 15:04

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('imatge', models.ImageField(blank=True, help_text='Carrega aquí la teva imatge.', upload_to='imatgesPerfil')),
                ('arxiu', models.FileField(blank=True, help_text='Carrega aquí el CV', upload_to='docPerfil')),
                ('descripcio', djrichtextfield.models.RichTextField(blank=True, null=True)),
                ('localitzacio', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), null=True, srid=4326)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('descripcio', djrichtextfield.models.RichTextField(blank=True, null=True)),
                ('pare', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Categoria')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('direccio', djrichtextfield.models.RichTextField()),
                ('poblacio', models.CharField(max_length=255)),
                ('cp', models.CharField(max_length=5)),
                ('telefon', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('web', models.URLField(blank=True)),
                ('localitzacio', django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(2.6875, 41.56), srid=4326)),
                ('descripcio', djrichtextfield.models.RichTextField(blank=True)),
                ('imatge', models.ImageField(blank=True, upload_to='imatgesCentre')),
                ('admins', models.ManyToManyField(blank=True, related_name='centres_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grau', models.CharField(choices=[('CFGM', 'Grau Mitjà'), ('CFGS', 'Grau Superior')], max_length=4)),
                ('codi', models.CharField(max_length=4, unique=True)),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('pladestudis', models.URLField(blank=True, null=True)),
                ('descripcio', djrichtextfield.models.RichTextField()),
                ('familia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ModulProfessional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('nom', models.CharField(max_length=255)),
                ('descripcio', djrichtextfield.models.RichTextField(blank=True)),
                ('cicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Cicle')),
            ],
            options={
                'verbose_name_plural': 'Moduls Professionals',
            },
        ),
        migrations.CreateModel(
            name='UnitatFormativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('nom', models.CharField(max_length=255)),
                ('descripcio', djrichtextfield.models.RichTextField()),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ModulProfessional')),
            ],
            options={
                'verbose_name_plural': 'Unitats Formatives',
            },
        ),
        migrations.AddField(
            model_name='centre',
            name='cicles',
            field=models.ManyToManyField(blank=True, related_name='centres', to='core.Cicle'),
        ),
        migrations.AddField(
            model_name='user',
            name='centre',
            field=models.ForeignKey(blank=True, help_text="Centre on està actualment matriculat l'alumne o el darrer centre on hi va estar.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Centre'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
