# Generated by Django 2.2.4 on 2019-09-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='codi',
            field=models.IntegerField(default=0),
        ),
    ]
