# Generated by Django 2.2.4 on 2019-09-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_centre_codi'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tos',
            field=models.BooleanField(default=False),
        ),
    ]
