# Generated by Django 2.2.4 on 2019-11-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_data_notificacio_tos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
