# Generated by Django 2.1.10 on 2019-08-21 15:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoneSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('descripcio', djrichtextfield.models.RichTextField(blank=True)),
                ('membres', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projecte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('descripcio', djrichtextfield.models.RichTextField()),
                ('inici', models.DateField(default=datetime.datetime.now)),
                ('final', models.DateField()),
                ('admins', models.ManyToManyField(help_text='Incloure aquí als professors implicats en el projecte', to=settings.AUTH_USER_MODEL)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Centre')),
                ('cicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Cicle')),
            ],
        ),
        migrations.CreateModel(
            name='Qualificacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(blank=True, null=True)),
                ('comentaris', djrichtextfield.models.RichTextField(blank=True)),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrum.Equip')),
            ],
            options={
                'verbose_name_plural': 'Qualificacions',
            },
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('descripcio', djrichtextfield.models.RichTextField(blank=True)),
                ('ordre', models.IntegerField(default=0)),
                ('mp', models.ManyToManyField(blank=True, help_text="Mòduls Professionals. NOTA: no apareixeran a en la CREACIÓ de la Spec, sinó en l'EDICIÓ", to='core.ModulProfessional')),
                ('pare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrum.Spec')),
                ('projecte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrum.Projecte')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('notes', djrichtextfield.models.RichTextField(blank=True)),
                ('inici', models.DateField()),
                ('final', models.DateField()),
                ('projecte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrum.Projecte')),
                ('specs', models.ManyToManyField(blank=True, help_text="NOTA: no apareixeran a en la CREACIÓ del Sprint, sinó en l'EDICIÓ", to='scrum.Spec')),
            ],
        ),
        migrations.AddField(
            model_name='qualificacio',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrum.Sprint'),
        ),
        migrations.AddField(
            model_name='equip',
            name='projecte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equips', to='scrum.Projecte'),
        ),
        migrations.AddField(
            model_name='donespec',
            name='qualificacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='done_specs', to='scrum.Qualificacio'),
        ),
        migrations.AddField(
            model_name='donespec',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrum.Spec'),
        ),
    ]
