# Generated by Django 2.2.4 on 2019-09-05 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spec',
            name='hores_estimades',
            field=models.FloatField(blank=True, default=0.0),
            preserve_default=False,
        ),
    ]
