# Generated by Django 2.2.4 on 2019-09-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0003_auto_20190908_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='hores_estimades',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
