# Generated by Django 2.2.4 on 2019-09-14 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0004_auto_20190914_0943'),
        ('scrum', '0004_auto_20190914_0946'),
    ]

    operations = [
    ]
