# Generated by Django 2.2.4 on 2019-11-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0006_auto_20191016_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='sprints',
            field=models.ManyToManyField(blank=True, related_name='specs', to='scrum.Sprint'),
        ),
    ]
