# Generated by Django 2.2.4 on 2019-11-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0007_auto_20191016_1948'),
        ('scrum', '0007_auto_20191108_1856'),
    ]

    operations = [
    ]
